// Generated from data/food_venues.csv
export type FoodVenue = {
  id: string;
  name: string;
  lat: number;
  lng: number;
  baseline?: number;
  city?: string;
};

export const FOOD_VENUES: FoodVenue[] = [
  { id: "pizza-palace", name: "Pizza Palace", lat: 53.5678, lng: -2.8845, baseline: 5, city: "Ormskirk" },
  { id: "burger-barn", name: "Burger Barn", lat: 53.5682, lng: -2.8851, baseline: 4, city: "Ormskirk" },
  { id: "sushi-spot", name: "Sushi Spot", lat: 53.5691, lng: -2.8832, baseline: 5, city: "Ormskirk" },
  { id: "mcdonalds-ormskirk", name: "McDonald's (Ormskirk)", lat: 53.5669, lng: -2.8874, baseline: 6, city: "Ormskirk" },
  { id: "kfc-ormskirk", name: "KFC (Ormskirk)", lat: 53.5672, lng: -2.8866, baseline: 6, city: "Ormskirk" },
  { id: "subway-ormskirk", name: "Subway (Ormskirk)", lat: 53.5680, lng: -2.8859, baseline: 5, city: "Ormskirk" },
  { id: "costa-ormskirk", name: "Costa Coffee (Ormskirk)", lat: 53.5681, lng: -2.8856, baseline: 5, city: "Ormskirk" },
  { id: "greggs-ormskirk", name: "Greggs (Ormskirk)", lat: 53.5682, lng: -2.8853, baseline: 5, city: "Ormskirk" },
  { id: "dominos-ormskirk", name: "Domino's Pizza (Ormskirk)", lat: 53.5675, lng: -2.8860, baseline: 6, city: "Ormskirk" },
  { id: "pizzaexpress-ormskirk", name: "PizzaExpress (Ormskirk)", lat: 53.5683, lng: -2.8849, baseline: 6, city: "Ormskirk" },
  { id: "wagamama-ormskirk", name: "Wagamama (Ormskirk)", lat: 53.5680, lng: -2.8852, baseline: 6, city: "Ormskirk" },
  { id: "mowgli-liverpool", name: "Mowgli Street Food (Liverpool)", lat: 53.4025, lng: -2.9849, baseline: 8, city: "Liverpool" },
  { id: "maray-liverpool", name: "Maray (Liverpool)", lat: 53.4030, lng: -2.9857, baseline: 7, city: "Liverpool" },
  { id: "bold-street-coffee", name: "Bold Street Coffee", lat: 53.4023, lng: -2.9839, baseline: 7, city: "Liverpool" },
  { id: "ruffle-restaurant", name: "Ruffle Bar & Kitchen", lat: 53.4041, lng: -2.9856, baseline: 7, city: "Liverpool" },
  { id: "wagamama-liverpool", name: "Wagamama (Liverpool ONE)", lat: 53.4049, lng: -2.9843, baseline: 7, city: "Liverpool" },
  { id: "five-guys-liverpool", name: "Five Guys (Liverpool ONE)", lat: 53.4046, lng: -2.9849, baseline: 7, city: "Liverpool" },
  { id: "nandos-liverpool-one", name: "Nando's (Liverpool ONE)", lat: 53.4043, lng: -2.9845, baseline: 7, city: "Liverpool" },
  { id: "turtle-bay-liverpool", name: "Turtle Bay (Liverpool)", lat: 53.4039, lng: -2.9851, baseline: 7, city: "Liverpool" },
  { id: "franco-manca-liverpool", name: "Franco Manca (Liverpool)", lat: 53.4040, lng: -2.9842, baseline: 7, city: "Liverpool" },
  { id: "dishoom-liverpool", name: "Dishoom (Liverpool)", lat: 53.4048, lng: -2.9858, baseline: 8, city: "Liverpool" },
  { id: "pho-liverpool", name: "Pho (Liverpool)", lat: 53.4047, lng: -2.9848, baseline: 7, city: "Liverpool" },
  { id: "cote-liverpool", name: "Côte Brasserie (Liverpool)", lat: 53.4049, lng: -2.9840, baseline: 7, city: "Liverpool" },
  { id: "dishoom-manchester", name: "Dishoom (Manchester)", lat: 53.4810, lng: -2.2435, baseline: 8, city: "Manchester" },
  { id: "hawksmoor-manchester", name: "Hawksmoor (Manchester)", lat: 53.4804, lng: -2.2441, baseline: 8, city: "Manchester" },
  { id: "bundobust-manchester", name: "Bundobust (Manchester)", lat: 53.4831, lng: -2.2433, baseline: 8, city: "Manchester" },
  { id: "rudys-manchester", name: "Rudy's Pizza (Manchester)", lat: 53.4822, lng: -2.2427, baseline: 8, city: "Manchester" },
  { id: "mowgli-manchester", name: "Mowgli Street Food (Manchester)", lat: 53.4817, lng: -2.2387, baseline: 8, city: "Manchester" },
  { id: "tattu-manchester", name: "Tattu (Manchester)", lat: 53.4826, lng: -2.2456, baseline: 8, city: "Manchester" },
  { id: "turtle-bay-manchester", name: "Turtle Bay (Manchester)", lat: 53.4808, lng: -2.2430, baseline: 7, city: "Manchester" },
  { id: "wagamama-manchester", name: "Wagamama (Manchester)", lat: 53.4825, lng: -2.2406, baseline: 7, city: "Manchester" },
  { id: "five-guys-manchester", name: "Five Guys (Manchester)", lat: 53.4820, lng: -2.2414, baseline: 7, city: "Manchester" },
  { id: "nandos-deansgate", name: "Nando's (Deansgate)", lat: 53.4786, lng: -2.2473, baseline: 7, city: "Manchester" },
  { id: "pho-manchester", name: "Pho (Manchester)", lat: 53.4830, lng: -2.2440, baseline: 7, city: "Manchester" },
  { id: "cote-manchester", name: "Côte Brasserie (Manchester)", lat: 53.4816, lng: -2.2451, baseline: 7, city: "Manchester" },
  { id: "turtle-bay-preston", name: "Turtle Bay (Preston)", lat: 53.7598, lng: -2.7036, baseline: 7, city: "Preston" },
  { id: "wagamama-preston", name: "Wagamama (Preston)", lat: 53.7596, lng: -2.7042, baseline: 7, city: "Preston" },
  { id: "five-guys-preston", name: "Five Guys (Preston)", lat: 53.7602, lng: -2.7040, baseline: 7, city: "Preston" },
  { id: "nandos-preston", name: "Nando's (Preston)", lat: 53.7597, lng: -2.7050, baseline: 7, city: "Preston" },
  { id: "cosmo-preston", name: "COSMO World Buffet (Preston)", lat: 53.7600, lng: -2.7032, baseline: 7, city: "Preston" },
  { id: "franco-manca-preston", name: "Franco Manca (Preston)", lat: 53.7595, lng: -2.7037, baseline: 7, city: "Preston" },
  { id: "cote-preston", name: "Côte Brasserie (Preston)", lat: 53.7599, lng: -2.7046, baseline: 7, city: "Preston" },
  { id: "mowgli-preston", name: "Mowgli Street Food (Preston)", lat: 53.7594, lng: -2.7041, baseline: 7, city: "Preston" },
  { id: "fish-chips-blackpool", name: "Seafront Fish & Chips (Central)", lat: 53.8160, lng: -3.0550, baseline: 7, city: "Blackpool" },
  { id: "wagamama-blackpool", name: "Wagamama (Blackpool)", lat: 53.8164, lng: -3.0556, baseline: 7, city: "Blackpool" },
  { id: "five-guys-blackpool", name: "Five Guys (Blackpool)", lat: 53.8166, lng: -3.0549, baseline: 7, city: "Blackpool" },
  { id: "nandos-blackpool", name: "Nando's (Blackpool)", lat: 53.8162, lng: -3.0552, baseline: 7, city: "Blackpool" },
  { id: "turtle-bay-blackpool", name: "Turtle Bay (Blackpool)", lat: 53.8168, lng: -3.0558, baseline: 7, city: "Blackpool" },
  { id: "pizzaexpress-blackpool", name: "PizzaExpress (Blackpool)", lat: 53.8161, lng: -3.0546, baseline: 6, city: "Blackpool" },
  { id: "franco-manca-blackpool", name: "Franco Manca (Blackpool)", lat: 53.8167, lng: -3.0547, baseline: 6, city: "Blackpool" },
  { id: "mcdonalds-blackpool-tower", name: "McDonald's (Tower Area)", lat: 53.8158, lng: -3.0539, baseline: 6, city: "Blackpool" },
  { id: "nandos-warrington", name: "Nando's (Warrington)", lat: 53.3910, lng: -2.5964, baseline: 7, city: "Warrington" },
  { id: "five-guys-warrington", name: "Five Guys (Warrington)", lat: 53.3913, lng: -2.5960, baseline: 7, city: "Warrington" },
  { id: "wagamama-warrington", name: "Wagamama (Warrington)", lat: 53.3916, lng: -2.5956, baseline: 7, city: "Warrington" },
  { id: "turtle-bay-warrington", name: "Turtle Bay (Warrington)", lat: 53.3912, lng: -2.5969, baseline: 7, city: "Warrington" },
  { id: "mcdonalds-warrington", name: "McDonald's (Warrington)", lat: 53.3920, lng: -2.5978, baseline: 6, city: "Warrington" },
  { id: "nandos-chester", name: "Nando's (Chester)", lat: 53.1920, lng: -2.8932, baseline: 7, city: "Chester" },
  { id: "five-guys-chester", name: "Five Guys (Chester)", lat: 53.1924, lng: -2.8930, baseline: 7, city: "Chester" },
  { id: "wagamama-chester", name: "Wagamama (Chester)", lat: 53.1922, lng: -2.8926, baseline: 7, city: "Chester" },
  { id: "turtle-bay-chester", name: "Turtle Bay (Chester)", lat: 53.1918, lng: -2.8938, baseline: 7, city: "Chester" },
  { id: "pizzaexpress-chester", name: "PizzaExpress (Chester)", lat: 53.1926, lng: -2.8934, baseline: 6, city: "Chester" },
  { id: "nandos-southport", name: "Nando's (Southport)", lat: 53.6466, lng: -3.0068, baseline: 7, city: "Southport" },
  { id: "five-guys-southport", name: "Five Guys (Southport)", lat: 53.6469, lng: -3.0071, baseline: 7, city: "Southport" },
  { id: "wagamama-southport", name: "Wagamama (Southport)", lat: 53.6467, lng: -3.0064, baseline: 7, city: "Southport" },
  { id: "mcdonalds-southport", name: "McDonald's (Southport)", lat: 53.6475, lng: -3.0080, baseline: 6, city: "Southport" },
];
