// Generated by scripts/import_venues.js - do not edit by hand
export type Venue = {
id: string;
name: string;
lat: number;
lng: number;
baseline?: number;
city?: string;
};

export const VENUES: Venue[] = [
  { id: "wetherspoons-court-leet", name: "Wetherspoons (Court Leet)", lat: 53.56807, lng: -2.885286, baseline: 6, city: "Ormskirk" },
  { id: "styles-bar", name: "Styles Bar", lat: 53.568418, lng: -2.885864, baseline: 5, city: "Ormskirk" },
  { id: "alpine-club-lodge", name: "Alpine Club Lodge", lat: 53.568039, lng: -2.883166, baseline: 5, city: "Ormskirk" },
  { id: "lime-tyger", name: "Lime Tyger", lat: 53.565594, lng: -2.883446, baseline: 5, city: "Ormskirk" },
  { id: "edge-hill-su", name: "Edge Hill Student Union", lat: 53.5602, lng: -2.87287, baseline: 7, city: "Ormskirk" },
  { id: "cricketers-liverpool", name: "The Cricketers", lat: 53.56555, lng: -2.8836, baseline: 5, city: "Ormskirk" },
  { id: "spiritz-bar", name: "Spiritz", lat: 53.56861, lng: -2.88468, baseline: 5, city: "Ormskirk" },
  { id: "number-twelve-bar", name: "Number Twelve Bar", lat: 53.56778, lng: -2.88641, baseline: 5, city: "Ormskirk" },
  { id: "murphys-irish-bar", name: "Murphy's Irish Bar", lat: 53.56692, lng: -2.88621, baseline: 5, city: "Ormskirk" },
  { id: "queens-head", name: "Queens Head", lat: 53.56695, lng: -2.88448, baseline: 5, city: "Ormskirk" },
  { id: "nordico-lounge", name: "Nordico Lounge", lat: 53.567, lng: -2.88485, baseline: 5, city: "Ormskirk" },
  { id: "the-green-room", name: "The Green Room", lat: 53.5671, lng: -2.88416, baseline: 5, city: "Ormskirk" },
  { id: "the-golden-lion", name: "The Golden Lion", lat: 53.56706, lng: -2.88391, baseline: 5, city: "Ormskirk" },
  { id: "tap-room", name: "Tap Room", lat: 53.56776, lng: -2.88566, baseline: 5, city: "Ormskirk" },
  { id: "liquid-bar", name: "Liquid Bar", lat: 53.56672, lng: -2.88342, baseline: 5, city: "Ormskirk" },
  { id: "tiny-tavern", name: "Tiny Tavern", lat: 53.56787, lng: -2.88574, baseline: 5, city: "Ormskirk" },
  { id: "deansgate-locks", name: "Deansgate Locks", lat: 53.4776, lng: -2.2429, baseline: 9, city: "Manchester" },
  { id: "factory-mcr", name: "Factory Manchester", lat: 53.4779, lng: -2.2356, baseline: 8, city: "Manchester" },
  { id: "revs-de-cuba-mcr", name: "Revolution De Cuba Manchester", lat: 53.481, lng: -2.244, baseline: 8, city: "Manchester" },
  { id: "the-printworks", name: "Printworks Manchester", lat: 53.483, lng: -2.24, baseline: 8, city: "Manchester" },
  { id: "albert-schloss", name: "Albert's Schloss", lat: 53.4809, lng: -2.2434, baseline: 8, city: "Manchester" },
  { id: "mojo-manchester", name: "MOJO Manchester", lat: 53.4814, lng: -2.2429, baseline: 7, city: "Manchester" },
  { id: "crazy-pedros", name: "Crazy Pedro’s", lat: 53.4832, lng: -2.2423, baseline: 7, city: "Manchester" },
  { id: "blues-kitchen-mcr", name: "The Blues Kitchen Manchester", lat: 53.4802, lng: -2.2448, baseline: 7, city: "Manchester" },
  { id: "night-and-day", name: "Night & Day Cafe", lat: 53.4846, lng: -2.2362, baseline: 7, city: "Manchester" },
  { id: "yes-manchester", name: "YES Manchester", lat: 53.4819, lng: -2.2339, baseline: 7, city: "Manchester" },
  { id: "cavern-club", name: "Cavern Club", lat: 53.408371, lng: -2.991573, baseline: 8, city: "Liverpool" },
  { id: "concert-square", name: "Concert Square", lat: 53.4039, lng: -2.9845, baseline: 9, city: "Liverpool" },
  { id: "heebie-jeebies", name: "Heebie Jeebies", lat: 53.4032, lng: -2.9853, baseline: 7, city: "Liverpool" },
  { id: "mccooleys-matthew-st", name: "Mccooley’s Matthew Street", lat: 53.409, lng: -2.9918, baseline: 7, city: "Liverpool" },
  { id: "mojo-liverpool", name: "MOJO Liverpool", lat: 53.4046, lng: -2.9862, baseline: 7, city: "Liverpool" },
  { id: "the-raz", name: "The Raz", lat: 53.4042, lng: -2.9869, baseline: 7, city: "Liverpool" },
  { id: "the-merchant", name: "The Merchant", lat: 53.4029, lng: -2.9841, baseline: 7, city: "Liverpool" },
  { id: "level-liverpool", name: "LEVEL Liverpool", lat: 53.4035, lng: -2.9856, baseline: 7, city: "Liverpool" },
  { id: "soho-liverpool", name: "Soho Liverpool", lat: 53.4048, lng: -2.9859, baseline: 7, city: "Liverpool" },
  { id: "preston-central", name: "Preston Central", lat: 53.7632, lng: -2.7046, baseline: 5, city: "Preston" },
  { id: "warehouse-preston", name: "Warehouse Preston", lat: 53.7599, lng: -2.7032, baseline: 6, city: "Preston" },
  { id: "switch-preston", name: "Switch Preston", lat: 53.7594, lng: -2.7021, baseline: 6, city: "Preston" },
  { id: "vinyl-tap-preston", name: "Vinyl Tap", lat: 53.7635, lng: -2.7071, baseline: 5, city: "Preston" },
  { id: "the-ferret", name: "The Ferret", lat: 53.7638, lng: -2.7084, baseline: 5, city: "Preston" },
  { id: "blackpool-tower-area", name: "Blackpool Tower Area", lat: 53.8155, lng: -3.0537, baseline: 6, city: "Blackpool" },
  { id: "popworld-blackpool", name: "Popworld Blackpool", lat: 53.8161, lng: -3.0543, baseline: 6, city: "Blackpool" },
  { id: "revolution-blackpool", name: "Revolution Blackpool", lat: 53.8165, lng: -3.0551, baseline: 6, city: "Blackpool" },
  { id: "walkabout-blackpool", name: "Walkabout Blackpool", lat: 53.8163, lng: -3.0549, baseline: 6, city: "Blackpool" },
  { id: "tiki-bar-blackpool", name: "Tiki Bar Blackpool", lat: 53.8172, lng: -3.0544, baseline: 5, city: "Blackpool" },
];
